- name: 'Upload config files for {{ interface.name }}'
  template:
    src: ifcfg.j2
    dest: '{{ interface.sysconfig_filename }}'

- name: 'Start interface {{ interface.name }} when it is not present'
  shell: ifup {{ interface.name }}
  when:
    (interface.name not in ansible_interfaces) and
    interface.activate

  

#  - name: lan42
#    activate: yes
#    sysconfig_filename: /etc/sysconfig/network-scripts/ifcfg-lan42
#    config: |
#      DEVICE=lan42
#      ONBOOT=yes
#      TYPE=Bridge
#      BOOTPROTO=static
#      NM_CONTROLLED=no
#      IPADDR=192.168.42.254
#      NETMASK=255.255.255.0